import { ParamsModel } from "./analyzer";
import { Patch, getKeyForParam } from "./parser";
import { PatchLibrary } from "./patchLibrary";
import { log } from "./utils/log";
import { uniqueNamesGenerator, adjectives, colors, names } from "unique-names-generator";

/**
 * Fully randomized patches, with real values from library
 */
export function createFullyRandomPatches(
  patchLibrary: PatchLibrary,
  paramModel: ParamsModel,
  number: number
): PatchLibrary {
  const newPatchLibrary: PatchLibrary = {
    patchRootFolder: patchLibrary.patchRootFolder + '/RANDOM',
    patches: []
  }
  for (let i = 0; i < number; i++) {
    const randomPatchIndex = Math.floor(
      Math.random() * patchLibrary.patches.length
    );
    const randomPatch: Patch = JSON.parse(
      JSON.stringify(patchLibrary.patches[randomPatchIndex])
    );

    for (const param of randomPatch.params) {
      const key = getKeyForParam(param);

      const randomParamValue = getRandomArrayItem(paramModel[key]!.values);
      let newParamValue = JSON.parse(JSON.stringify(randomParamValue));

      if (param.value !== newParamValue) {
        // log.debug(`  ${key}: Old: ${param.value} -> New: ${newParamValue}`);
      }
      param.value = newParamValue;
    }

    const randomName = uniqueNamesGenerator({
      dictionaries: [adjectives, colors, names],
      separator: " ",
      style: "capital",
    });

    randomPatch.filePath = `/RND ${randomName}.h2p`;
    randomPatch.presetName = `RND ${randomName}`;
    randomPatch.meta = [
      {
        "key": "Author",
        "value": "Random Generator"
      },
      {
        "key": "Description",
        "value": "Fully random patch, generated by https://github.com/Fannon/u-he-synth-preset-randomizer"
      }
    ],

    log.info(`Generated random Patch: ${randomPatch.filePath}`);
    newPatchLibrary.patches.push(randomPatch)
  }
  return newPatchLibrary;
}

//////////////////////////////////////////
// HELPER FUNCTIONS                     //
//////////////////////////////////////////

export function getRandomArrayItem(list: any[]) {
  return list[Math.floor(Math.random() * list.length)];
}
